spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/toDoList
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop